### ISSUE TITLE
gpu的构思

### ISSUE THREAD

**Issue by afpro** [dbsxdbsx/only_torch#2]
偶然看到这个项目 看到简介说只做cpu 觉得挺可惜
要不要考虑直接用 https://wgpu.rs/ 这玩意 跨平台交给他

**Comment by afpro** [comment]
https://docs.rs/wgpu/latest/wgpu/struct.ComputePass.html 这玩意支持纯计算

**Comment by dbsxdbsx** [comment]
感谢建议。也许后期成熟了发现性能不够了会再考虑。
